tag cloudflared docker image with latest
cloudflare/cloudflared pull request #243
Opened 2020-09-28 22:55 UTC by acrogenesis

This updates the docker build to also include the `latest` tag which should default to the latest version available (Fixes #242).

2020-09-29 22:21 UTC, chungthuang approved these changes

2020-09-30 02:58 UTC, adamchalmers approved these changes

2020-09-30 11:07 UTC, TownLake requested changes
Thanks for the PR; putting a note here - a member of our team found an issue with the latest usage here and we're going to have them take a look today.

2020-09-30 14:11 UTC, Michael9127 reviewed
This Make target actually only builds images for local use and testing. We have internal infrastructure that is responsible for building, tagging, and publishing images for dockerhub. The PR is appreciated but unfortunately this is a change that is going to have to be made internally in a different place.

2020-09-30 14:25 UTC, closed without merging