Update README.md
cloudflare/cloudflared pull request #256
Opened 2020-11-04 20:35 UTC by TownLake

2020-11-04 21:49 UTC, adamchalmers requested changes

2020-11-04 21:49 UTC, adamchalmers commented on README.md
> +* You can [install on macOS](https://developers.cloudflare.com/argo-tunnel/getting-started/installation#macos) via Homebrew or by downloading the latest Darwin amd64 release
Can we change "downloading the latest Darwin amd64 release" to link to the downloads page

2020-11-04 21:49 UTC, adamchalmers commented on README.md
> +* Route traffic to that Tunnel with [DNS records in Cloudflare](https://developers.cloudflare.com/argo-tunnel/routing-to-tunnel/dns)
I'd prefer combining these: "Route traffic to that Tunnel with DNS records in Cloudflare, or with a Cloudflare Load Balancer.

2020-11-05 09:39 UTC, chungthuang approved these changes

2020-11-05 21:54 UTC, adamchalmers approved these changes

2020-11-06 14:06 UTC, merged

2025-02-07 03:22 UTC, RAMYARMEMARI reviewed
**Describe the feature you'd like**
A clear and concise description of the feature. What problem does it solve for you?

**Describe alternatives you've considered**
Are there any alternatives to solving this problem? If so, what was your experience with them?