Update link to documentation for running as a service.
cloudflare/cloudflared pull request #257
Opened 2020-11-07 15:09 UTC by jwalton

When you run cloudflared in Linux, it'll say:

```
cloudflared will not automatically update when run from the shell.
To enable auto-updates, run cloudflared as a service:
https://developers.cloudflare.com/argo-tunnel/reference/service/
```

This documentation seems to be out of date, however, and [causing some confusion](https://github.com/cloudflare/cloudflared/issues/251).  There also doesn't seem to be a way to actually navigate to this page from the [Argo Tunnel docs](https://developers.cloudflare.com/argo-tunnel/).  Note that when you visit the link above, none of the sections in the table of contents on the left side of the page are expanded.

So, this PR replaces this link with what seems to be more up-to-date documentation at https://developers.cloudflare.com/argo-tunnel/create-tunnel/run-as-service.

2020-11-07 15:11 UTC, TownLake commented
Thank you for taking the time to update this (and for catching it). We'll take a look now.

2021-03-09 17:20 UTC, TownLake approved these changes

2021-03-09 17:48 UTC, nmldiegues requested changes

2021-03-09 17:48 UTC, nmldiegues commented on README.md
> +* You can [install on macOS](https://developers.cloudflare.com/argo-tunnel/getting-started/installation#macos) via Homebrew or by downloading the [latest Darwin amd64 release](https://github.com/clou
Need to replace the first link with https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation#macos

2021-03-09 17:48 UTC, nmldiegues commented on README.md
> +Contains the command-line client for Argo Tunnel, a tunneling daemon that proxies any local webserver through the Cloudflare network. Extensive documentation can be found in the [Argo Tunnel section]
This link is now redirecting to https://developers.cloudflare.com/cloudflare-one/connections/connect-apps , so we may as well link to it directly

2021-03-09 17:48 UTC, nmldiegues commented on README.md
> +* Binaries, Debian, and RPM packages for Linux [can be found here](https://developers.cloudflare.com/argo-tunnel/getting-started/installation#linux)
Link should be replaced with https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation#linux

2021-03-09 17:48 UTC, nmldiegues commented on README.md
> +* You can install on Windows machines with the [steps here](https://developers.cloudflare.com/argo-tunnel/getting-started/installation#windows)
Link should be replaced with https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation#windows

2021-03-09 17:48 UTC, nmldiegues commented on README.md
> +* Route traffic to that Tunnel with [DNS records in Cloudflare](https://developers.cloudflare.com/argo-tunnel/routing-to-tunnel/dns) or with a [Cloudflare Load Balancer](https://developers.cloudflare
Same as above for:
 - https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/routing-to-tunnel/dns
 - https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/routing-to-tunnel/lb

2021-03-09 17:48 UTC, nmldiegues commented on README.md
> +Want to test Argo Tunnel before adding a website to Cloudflare? You can do so with TryCloudflare using the documentation [available here](https://developers.cloudflare.com/argo-tunnel/learning/tryclo
Same as above for https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/trycloudflare

2021-03-09 17:48 UTC, nmldiegues commented on cmd/cloudflared/macos_service.go
> +			"For more information, visit https://developers.cloudflare.com/argo-tunnel/create-tunnel/run-as-service")
Broken link, must be https://developers.cloudflare.com/argo-tunnel/run-tunnel/run-as-service

2021-03-09 17:48 UTC, nmldiegues commented on cmd/cloudflared/updater/update.go
> +	noUpdateInShellMessage        = "cloudflared will not automatically update when run from the shell. To enable auto-updates, run cloudflared as a service: https://developers.cloudflare.com/argo-tunne
Must be https://developers.cloudflare.com/argo-tunnel/run-tunnel/run-as-service

2021-03-09 17:48 UTC, nmldiegues commented on cmd/cloudflared/windows_service.go
> +	windowsServiceUrl         = "https://developers.cloudflare.com/argo-tunnel/create-tunnel/run-as-service"
Must be https://developers.cloudflare.com/argo-tunnel/run-tunnel/run-as-service

2023-01-09 16:33 UTC, closed without merging