Fix macOS service installation launch template
cloudflare/cloudflared pull request #341
Opened 2021-03-26 09:02 UTC by allending

The current version of cloudflared (2021.3.2 at time of commit)
requires additional arguments to start a tunnel. Running 'cloudflared'
on its own does not run a tunnel with the default configuration.

This is behavior that has changed from previous versions of cloudflared,
where no arguments were required for starting/running a tunnel with the
default configuration behavior.

This fixes https://github.com/cloudflare/cloudflared/issues/327.

2021-04-02 00:49 UTC, ytbigvinny27 requested changes
Delete all

2021-05-04 20:55 UTC, ipostelnik requested changes
We have users that rely on running cloudflared in "client" mode which doesn't use these arguments. We need to continue to support this.

2021-05-06 12:34 UTC, adamfeldman commented
@ipostelnik could this modal behavior be put behind a config flag? Last I checked, when reporting this pain point in March, there was no documentation about running `cloudflared` as a service in "client" vs. "tunnel" mode. [Please see this comment on the related issue](https://github.com/cloudflare/cloudflared/issues/327#issuecomment-833485533). Thank you!

2023-06-01 01:47 UTC, 01SMD approved these changes

2023-12-14 16:28 UTC, joliveirinha commented
closing due to age

2023-12-14 16:28 UTC, closed without merging

2025-01-07 18:09 UTC, adampatterson commented
@joliveirinha  This is still an actual issue though. At least on MacOS

https://github.com/cloudflare/cloudflared/issues/327