Add support for taking named tunnel credentials from an environment var
cloudflare/cloudflared pull request #463
Opened 2021-09-09 12:06 UTC by nint8835

# Description
Resolves #457.

Adds a new flag, `credentials-contents`, to act as an alternative to `credentials-file`. This flag has an environment variable of `TUNNEL_CRED_CONTENTS` attached, allowing providing of named tunnel credentials via an environment variable. This flag, if provided, causes `subcommandContext.findCredentials` to load the credentials from the value of the flag, rather than trying to find a file on disk to load from.

# Testing
- I have added unit tests for the behaviour I implemented
- I have tested locally by running the following:
```bash
make cloudflared
export TUNNEL_CRED_CONTENTS=$(cat ~/.cloudflared/TUNNEL_UUID.json)
./cloudflared tunnel run --url http://localhost:5000 TUNNEL_UUID
``` 
- I have successfully gotten `cloudflared` running on Fargate in AWS ECS, and ensured it is functioning properly

2021-09-09 13:30 UTC, nmldiegues reviewed
Thanks for this contribution.

I only have minor comments, otherwise LGTM

2021-09-09 13:30 UTC, nmldiegues commented on cmd/cloudflared/tunnel/subcommands.go
> +		Usage:   "Contents of the tunnel credentials JSON file to use.",
Consider adding here some description that relates this with `credentials-file`:  if both are set, then `credentials-contents` takes precedence.

2021-09-09 13:30 UTC, nmldiegues commented on cmd/cloudflared/tunnel/subcommand_context_test.go
> +			name: "TUNNEL_CRED_CONTENTS given contains old credentials file",
s/file/contents/

2021-09-09 13:30 UTC, nmldiegues commented on cmd/cloudflared/tunnel/subcommand_context_test.go
> +			name: "TUNNEL_CRED_CONTENTS given contains new credentials file",
same as above

2021-09-09 14:14 UTC, nmldiegues approved these changes

2021-09-13 15:43 UTC, sssilver requested changes
Can we squash before getting this merged?

2021-09-13 19:12 UTC, sssilver approved these changes

2021-09-13 19:13 UTC, merged